project_id = "ojxzssooylmydystjvdo"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.sync-listing]
verify_jwt = false

[functions.auth-status]
verify_jwt = false

[functions.get-listings]
verify_jwt = false

[functions.dashboard-overview]
verify_jwt = false

[functions.amazon-inventory-sync]
verify_jwt = false

[functions.send-inventory-notification]
verify_jwt = false

[functions.generate-titles]
verify_jwt = false

[functions.get-calculator-settings]
verify_jwt = false
